### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by noraceppic** [formeka/sf-00#1]
bonjour mehdi
j 'essaye d'installer symfony 
 après cette commande sur pawersell y avis une autre commande à taper mais je la trouve pas 
 irm get.scoop.sh | iex

**Comment by formeka** [comment]
Bonjour nora,
effectue cette suite de commande :
`Set-ExecutionPolicy RemoteSigned -scope CurrentUser`
`iwr -useb get.scoop.sh | iex`
`scoop install symfony-cli`
`symfony -v`

**Comment by formeka** [comment]
Nora,
as tu resussi à installer symfony ?
