### ISSUE TITLE
php

### ISSUE THREAD

**Issue by BouazziH** [formeka/sf-00#2]
Bonjour mehdi 
je viens vers toi  vu que j'ai pas trouver de reponse et je ne veux pas perdre plus de temps j'ai installer symfony mais quand je cree mon projet j'ai  un message de no PHP binaries detected

**Comment by formeka** [comment]
Bonjour Hamza,

si tu as xampp d'installé sur ta machine ,c'est que php est installé.

Tu me confirme que xammp est installé sur ta machine ?

**Comment by BouazziH** [comment]
oui il est installé

**Comment by formeka** [comment]
Que donne  `php -v`

**Comment by BouazziH** [comment]
command not found c'est ca que je ne comprend pas

**Comment by formeka** [comment]
Il va falloir ajouter php dans tes variables d'environnement ...

Sais tu le faire ?

**Comment by BouazziH** [comment]
je vais voir le faire

**Comment by formeka** [comment]
[(https://wtf.roflcopter.fr/pics/6t2MszTj/EKnLHSc3.png](https://wtf.roflcopter.fr/pics/6t2MszTj/EKnLHSc3.png)
[https://wtf.roflcopter.fr/pics/vO45jyB6/8Gpff42C.png](https://wtf.roflcopter.fr/pics/vO45jyB6/8Gpff42C.png)
[https://wtf.roflcopter.fr/pics/XuqgPK5O/o6GebwrL.png](https://wtf.roflcopter.fr/pics/XuqgPK5O/o6GebwrL.png)
[https://wtf.roflcopter.fr/pics/x42D4pQb/KxVF9aNS.png](https://wtf.roflcopter.fr/pics/x42D4pQb/KxVF9aNS.png)

Ensuite redemarrer l'ordinateur et reverifier `php -v`

Installer aussi [composer](https://getcomposer.org/download/) si ce n'est pas fait.

**Comment by BouazziH** [comment]
salut mehdi c'est bon merci mais fallait deja que je trouve le chemin d'instalation de php qui  etait pas indiquer sur mon path apres fallait rajouter un ; et le taper apres donc voila c etait ca mon erreur merci pour ton aide en tout cas
