### ISSUE TITLE
symfony server

### ISSUE THREAD

**Issue by sanjoywong** [formeka/sf-00#3]
Bonjour Mehdi，

          Je ne sais pas pourquoi le server ne march pas. J'ai  essaye de sample controller luckynumber, it ne marche pas aussi.

le log : 
  unable to detect the front controller, disabling the PHP server error="Passthru script \"/index.php\" does not exist under C:\\xampp\\htdocs\\sf-00\\: CreateFile C:\\xampp\\htdocs\\sf-00\\index.php: The system cannot find the file specified."

merci.

Shengzhuo WANG

**Comment by formeka** [comment]
Quel est la commande que tu as tapé ?

Est tu bien dans le repertoire de ton application symfony ?

**Comment by Coco0105** [comment]
An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'agence_id' cannot be null
   Que faire ?

**Comment by formeka** [comment]
> An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'agence_id' cannot be null Que faire ?

Quel est la command que vous avez entré ?

**Comment by formeka** [comment]
> oui, c'est pas le repertoire correct, je dois enter ceppic.
> 
> Maintenant routes.yaml marche mais #[Route('/lucky/number/{max}', name: 'app_lucky_number')] ne marche pas.
> 
> Merci

Ce que tu demande n'est pas du tout demandé dans le readme !?
A aucun moment je ne parle de "lucky number" !!!

**Comment by sanjoywong** [comment]
Je sais , j'ai fini home et excute 'composer require annotations' .

'route / ' marche dans le routes.yaml ,
#[Route('/', name: 'app_home')] ne marche pas

**Comment by sanjoywong** [comment]
#[Route('/', name: 'app_home')]     dans HomeController.php 
ne marche pas

**Comment by formeka** [comment]
Tu n'a rien à faire car `symfony console make:controller` te crée le controlleur et le fichier `twig`qui va avec .

**Comment by formeka** [comment]
> Je sais , j'ai fini home et excute 'composer require annotations' .
> 
> 'route / ' marche dans le routes.yaml , #[Route('/', name: 'app_home')] ne marche pas


Tu n'a pas à faire `composer require annotations` car quand on fait une installation avec `symfony new ceppic --webapp` , le fait de mettre `webapp`(installation complete pour une une application web) le module `annotations` sera installé.

**Comment by sanjoywong** [comment]
ok,  j'ajoute HomeController.php par créer la fichier , ne fait la command 'symfony console make:controller HomeController'.

je comprends.

Merci
